version: '2'
services:
  master-lv:
    image: lvious/lvxq:tsa
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: master_tsa.py
      MONGOHOST: 54.161.160.206
      REDISHOST: 54.161.160.206
      MONGOPORT: 31017
      REDISPORT: 6479      
    labels:
      io.rancher.scheduler.affinity:host_label: spider=master
      io.rancher.container.pull_image: always

  worker-lv:
    image: lvious/lvxq:tsa
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: worker_tsa.py
      MONGOHOST: 54.161.160.206
      REDISHOST: 54.161.160.206
      MONGOPORT: 31017
      REDISPORT: 6479
    labels:
      io.rancher.scheduler.affinity:host_label: spider=worker
      io.rancher.container.pull_image: always

  writer-lv:
    image: lvious/lvxq:tsa
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: writer_tsa.py
      MONGOHOST: 54.161.160.206
      REDISHOST: 54.161.160.206
      MONGOPORT: 31017
      REDISPORT: 6479
    labels:
      io.rancher.scheduler.affinity:host_label: spider=worker
      io.rancher.container.pull_image: always
