version: '2'
services:
  master-lv:
    image: lvious/lvxq:tsa
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: master_tsa.py
    labels:
      io.rancher.scheduler.affinity:host_label: spider=master
      io.rancher.container.pull_image: always

  worker-lv:
    image: lvious/lvxq:tsa
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: worker_tsa.py
      MONGOHOST: localhost
      REDISHOST: localhost
    labels:
      io.rancher.scheduler.affinity:host_label: spider=worker
      io.rancher.container.pull_image: always
